export class ProductEntity {
  constructor(
    public readonly id: string,
    public name: string,
    public fantasyName: string,
    public nameFilter: string,
    public ezId: number | null,
    public providerId: string | null,
    public categoryId: string | null,
    public ref: string | null,
    public unitId: string | null,
    public colorId: string | null,
    public sizeId: string | null,
    public designId: string | null,
    public shapeId: string | null,
    public originId: string | null,
    public modelId: string | null,
    public ncm: string | null,
    public cst: string | null,
    public ean: string | null,
    public buyPrice: number | null,
    public sellPrice: number | null,
    public hasSeals: boolean | null,
    public amountStart: number | null,
    public amountSold: number | null,
    public amountUnlimited: boolean,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
  ) {}
}
